from flask import Flask, request, jsonify, send_file
import os
from model import predict_image, model
from gradcam import get_gradcam
from utils import get_doctor, get_diet, get_hospitals
from reportlab.pdfgen import canvas
from flask import render_template
from flask_cors import CORS
from flask import send_from_directory
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
from flask import send_file

app = Flask(__name__)

os.makedirs("uploads", exist_ok=True)
os.makedirs("reports", exist_ok=True)


app = Flask(__name__, template_folder="../frontend/templates", static_folder="../frontend/static")

@app.route("/")
def home():
    return render_template("index.html")

@app.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_from_directory('uploads', filename)

@app.route("/predict", methods=["POST"])
def predict():
    try:
        file = request.files["file"]
        location = request.form.get("location", "Your City")
        patient_name = request.form.get("patientName", "Unknown")

        filepath = os.path.join("uploads", file.filename)
        file.save(filepath)

        disease, confidence = predict_image(filepath)

        grad_path = os.path.join("uploads", "grad_" + file.filename)
        get_gradcam(filepath, model, grad_path)

        return jsonify({
            "disease": disease,
            "confidence": round(confidence * 100, 2),
            "doctor": get_doctor(disease),
            "diet": get_diet(disease),
            "hospitals": get_hospitals(location),
            "gradcam": grad_path,
            "patientName": patient_name,
            "originalImage": filepath,
})

    except Exception as e:
        print("❌ ERROR:", e)
        return jsonify({"error": str(e)})
    print("Grad path:", grad_path)

@app.route("/report", methods=["POST"])
def report():
    
    data = request.json
    pdf_path = "reports/report.pdf"

    # Ensure reports folder exists
    os.makedirs("reports", exist_ok=True)

    doc = SimpleDocTemplate(pdf_path)
    styles = getSampleStyleSheet()

    content = []

    # Title
    content.append(Paragraph("<b>AI X-Ray Diagnosis Report</b>", styles["Title"]))
    content.append(Spacer(1, 10))

    # Date
    content.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # Patient Name
    content.append(Paragraph(f"<b>Patient Name:</b> {data.get('patientName','Unknown')}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # Diagnosis Info
    content.append(Paragraph(f"<b>Disease:</b> {data.get('disease','-')}", styles["Normal"]))
    content.append(Paragraph(f"<b>Confidence:</b> {data.get('confidence','-')}%", styles["Normal"]))
    content.append(Paragraph(f"<b>Doctor:</b> {data.get('doctor','-')}", styles["Normal"]))
    content.append(Paragraph(f"<b>Diet:</b> {data.get('diet','-')}", styles["Normal"]))
    content.append(Spacer(1, 10))

    # Hospitals
    content.append(Paragraph("<b>Recommended Hospitals:</b>", styles["Heading2"]))
    for h in data.get("hospitals", []):
        content.append(Paragraph(f"- {h}", styles["Normal"]))

    content.append(Spacer(1, 15))

    # =========================
    # GRAD-CAM IMAGE
    # =========================
    content.append(Paragraph("<b>Detected Affected Area (Grad-CAM):</b>", styles["Heading2"]))

    # Get raw path
    raw_path = data.get("gradcam", "")
    print("🧪 Raw Grad path:", raw_path)

    # Extract filename
    filename = os.path.basename(raw_path)

    # Build correct path
    grad_path = os.path.join("uploads", filename)
    print("✅ Grad path:", grad_path)

    # Add image if exists
    if os.path.exists(grad_path):
        print("✅ Image FOUND")
        content.append(Image(grad_path, width=350, height=350))
    else:
        print("❌ Image NOT FOUND")
        content.append(Paragraph("Grad-CAM image not available", styles["Normal"]))

    content.append(Spacer(1, 10))

    # Footer
    content.append(Paragraph("Generated by X-Ray Vision Disease Detection System", styles["Normal"]))

    doc.build(content)

    return send_file(pdf_path, as_attachment=True)

if __name__ == "__main__":
    app.run(debug=True)
